export type ChecklistItem = { n: number; text: string };

export const CHECKLIST_TRITURATORE: ChecklistItem[] = [
  { n: 1, text: `CONTROLLO ALIMENTAZIONE BATTERIE: tensione Batterie 24VDC e tensione Batterie tampone 24VDC` },
  { n: 2, text: `ACCENSIONE QUADRO ELETTRICO DA INTERRUTTORE GENERALE: commutatore su Batterie, Verificare la presenza delle viti sui poli aggiuntivi. Controllare che allo stacca batterie sia stato interrotto il polo positivo e non il negativo` },
  { n: 3, text: `CONTROLLO TENSIONE IN INGRESSO: tensione 24VDC` },
  { n: 4, text: `VERIFICA SERRAGGIO DI TUTTI I MORSETTI` },
  { n: 5, text: `VERIFICA DI TUTTI I DIODI: scollegando i fili + e - delle batterie nel quadro (10120 e 10121) il PLC deve rimanere acceso. Con le batterie spente la centralina del motore diesel deve rimanere spenta` },
  { n: 6, text: `VERIFICA DI TUTTI I MAGNETOTERMICI, inclusa verifica protezione 24V, 110V, 230V` },
  { n: 7, text: `VERIFICA DI TUTTI I RELE'` },
  { n: 8, text: `VERIFICA DI TUTTI I FUSIBILI (PRESENZA E FUNZIONAMENTO)` },
  { n: 9, text: `SIMULARE CIRCUITO DI EMERGENZA: provare tutte le Emergenze e verificare che vengano tagliate le alimentazioni` },
  { n: 10, text: `CONTROLLO INGRESSI DIGITALI` },
  { n: 11, text: `SIMULARE USCITE DIGITALI: alimentare con 24VDC il contatto del relè` },
  { n: 12, text: `IMPOSTARE PARAMETRI SU HMI (vedi lista completa in appendice A)` },
  { n: 13, text: `VERIFICA ANALOGICHE: da HMI, Pagina Servizi controllare: Temperatura olio centralina, Temperatura Ritorno Rulli - devono essere a temperatura ambiente (FARE FOTO)` },
  { n: 14, text: `ACCENDERE MOTORE: Inserire comandi da pulsante, su quadro motore mettere in manuale, resettare, premere start (il motore si avvia). Se motore non si avvia ponticellare su quadro motore Stop Motore e Consenso Avviamento e verificare problema nel QE` },
  { n: 15, text: `VERIFICARE ELETTROPOMPA GRASSO: Tramite l'ausilio della pagina dedicata presente a supervisore, premendo il pulsante a schermo dedicato, verificare senso di rotazione del girante. Tramite lo stesso pulsante verificare la transizione del sensore montato sul massello durante il funzionamento della pompa. Se presenti, verificare il funzionamento dei sensori sui singoli circuiti di ingrassaggio procedendo a tappare uno dopo l'altro tutti e 4 i circuiti e verificare che per ogni circuito tappato si attivi il relativo sensore di intasamento.Verificare che se inserito, qualora il circuito di ingrassaggio non conclude il numero di cicli prefissati nel tempo di lavoro viene visualizzato un allarme HMI ed il ciclo automatico si interrompe` },
  { n: 16, text: `VERIFICA FUNZIONAMENTO RADIOCOMANDO: verifica emergenza, stop, cambio velocità (se olio sotto 15° non funziona), comando manuale dei rotori (1 e 2, avanti indietro), verifica se va inversioni, verifica collegamento con ricevitore` },
  { n: 17, text: `VERIFICA PRESSIONE RULLI: verificare che le pressioni sui trasduttori (280, 280, 180 bar) corrispondano a quelle impostate sull'HMI. Verifica pressione analogica riscaldo/raffreddo.` },
  { n: 18, text: `VERIFICA PROPORZIONALE RULLO 1: da radiocomando selezionare rullo 1 avanti in manuale, verificare che la pressione del rullo 1 salga, se comando avanti e la pressione non sale provare indietro, se la pressione sale sono invertite le pipette` },
  { n: 19, text: `VERIFICA PROPORZIONALE RULLO 2: da radiocomando selezionare rullo 2 avanti in manuale, verificare che la pressione del rullo 2 salga, se comando avanti e la pressione non sale provare indietro, se la pressione sale sono invertite le pipette` },
  { n: 20, text: `VERIFICA PROPORZIONALE RISCALDO: Avviare ciclo automatico da radiocomando, per avviare ciclo automatico l'olio deve essere >15°. Nella pagina dei servizi si vede la % di chiusura della valvola che sale, verificare che anche la pressione del ricircolo salga di pari passo (120 - 160 bar)` },
  { n: 21, text: `VERIFICA RAFFREDDAMENTO: quando superiamo i 40°C parte il raffeddamento, verificare la EV 1.156A (Raffred.) - 1.156B (Riscaldo). Sopra la seconda soglia (45°C) parte anche EV per i ventilatori (YV8015 Diesel - Y170.3 Elettrico)` },
  { n: 22, text: `PROVA INVERSIONI METODO 1 CON VALVOLE: modificare il parametro "Pressione per inversione" impostare 80 bar, avviare ciclo automatico e verificare che esegua i cicli. Chiudere la valvola del rullo da controllare, verificare che la pressione superi gli 80 bar e che avvenga l'inversione. Reimpostare parametro a 280 bar.` },
  { n: 23, text: `PROVA INVERSIONI METODO 2: modificare il parametro "Pressione per inversione" impostare 80 bar, avviare ciclo automatico e verificare che esegua i cicli di inversione, dopo 4 tentativi consecutivi deve arrestare ciclo automatico. Reimpostare parametro a 280 bar. Verificare che i contatori "numero di inversioni" e "numero stop ciclo" registrino i valori corretti; dopo 4 inversioni il ciclo autoamtico si ferma ed il contatore stop ciclo deve conteggiare 1 stop ciclo.` },
  { n: 24, text: `VERIFICARE FUNZIONAMENTO RESISTENZE: collegare 400 VAC (versione Diesel: su HMI pagina Centralina attivare Riscaldo con Resistenze). Verificare Tensione su Resistenze (400 VAC)` },
  { n: 25, text: `VERIFICARE FUNZIONAMENTO SEMAFORO E SIRENA: simulare uscite PLC, controllo colori semaforo. Controllo funzionamento sirena in caso di avviamento ciclo automatico. Controllo funzionamento sirena in caso di allarme critico: - minimo livello olio; - saracinesche chiuse; - motore avaria; - emergenza; - olio troppo caldo; Luce verde: macchina pronta; Luce verde lampeggiante: macchina in lavoro ciclo automatico; Luce arancione lampeggiante: inversione; Luce rossa fissa: emergenza o allarme critico; Luce rossa lampeggiante: allarme non critico: - allarme grasso;` },
  { n: 26, text: `TARATURA TERMOSTATI CENTRALINA IDRAULICA: 75°C Tmax - 10°C Tmin` },
  { n: 27, text: `VERIFICA CORRETTA CONNESSIONE CAVI GALLEGGIANTE SERBATOIO DIESEL: - nero XM5 a terra - bianco XM6 (segnale) T - rosso (riserva) W Utilizzare apposito serbatoio appendice per diesel e collegare galleggiante, tubo pescaggio e tubo scarico diesel` },
  { n: 28, text: `VERSIONE DIESEL: RIPRISTINARE COLLEGAMENTO TUBI GASOLIO ANDATA (MOTORE), RITORNO (SERBATOIO) E GALLEGGIANTE AL SERBATOIO DIESEL SOTTO IL MOTORE` },
  { n: 29, text: `VERIFICA CORRETTA CONNESSIONE CAVI GALLEGGIANTE CENTRALINA OLIO E CORRETTO FUNZIONAMENTO DEL GALLEGGIANTE (allarme livello minimo olio). Provare a staccare pipetta e controllare funzionamento` },
  { n: 30, text: `CONTROLLO N°3 SPIE FILTRI OLIO CENTRALINA: - verde: OK - arancio: filtro intasato 75% - rossa: filtro intasato 100%` },
  { n: 31, text: `VERIFICA CHE NON CI SIANO ALLARMI SUI FILTRI OLIO CENTRALINA FINO A 30°C TEMPERATURA OLIO CENTRALINA` },
  { n: 32, text: `VERIFICA CHIUSURE PASSAGGIO OLIO CENTRALINA (FINE CORSA SARACINESCHE ASPIRAZIONE) E RELATIVI ALLARMI. Test: - a macchina spenta non si deve avviare - a macchina accesa si deve spegnere` },
  { n: 33, text: `CONTROLLO FUNZIONAMENTO VALVOLA CAMBIO CILINDRATA (utilizzando i manometri). Cambiare nell'HMI la pressione di taratura per simulare il cambio velocità.` },
  { n: 34, text: `VERIFICARE FUNZIONAMENTO LUCI ILLUMINAZIONE` },
  { n: 35, text: `VERIFICA PRESENZA FUSIBILI DI SCORTA` },
  { n: 36, text: `VERIFICA SET UP LINGUE HMI` },
  { n: 37, text: `VERIFICA SET UP LINGUA PANNELLO MOTORE` },
  { n: 38, text: `VERIFICA SET UP SOGLIE CONDIZIONATORE E TERMOSTATO` },
  { n: 39, text: `VERIFICA VENTOLA QUADRO ELETTRICO` },
  { n: 40, text: `VERIFICA ASSENZE PERDITE OLIO` },
  { n: 41, text: `TEST EWON REGISTRAZIONE E CONNETTIVITA' CON SERVER ZATO` },
  { n: 42, text: `TEST LETTURA DATI MOTORE DIESEL O ELETTRICO` },
  { n: 43, text: `VERIFICA LETTURA ALLARME DA CONDIZIONATORE` },
  { n: 44, text: `VERIFICA SENSO ROTAZIONE VENTOLE RAFFREDDAMENTO OLIO` },
  { n: 45, text: `VERIFICA CHE NON CI SIANO SURRISCALDAMENTI ANOMALI SU COMPONENTI DEL CIRCUITO IDRAULICO IN SPECIAL MODO SU POMPE E MOTORI` },
  { n: 46, text: `VERIFICA LIVELLO OLIO MOTORE DIESEL` },
  { n: 47, text: `VERIFICA LIVELLO LIQUIDO DI RAFFREDDAMENTO MOTORE DIESEL` },
  { n: 48, text: `VERIFICA EVENTUALI PERDITE FUMI MARMITTA` },
  { n: 49, text: `VERIFICA PRESENZA PULSANTIERA AUX,SCATOLA GRASSO+PROLUNGA,SEMAFORO A FINE COLLAUDO` },
  { n: 50, text: `VERIFICA SENSO DI ROTAZIONE MOTORI ELETTRICI (VERIFICARE PRESENZA FRECCIA SENSO DI ROTAZIONE CORRETTA PRESENTE SULLA VENTOLA DI RAFFREDDAMENTO DEL MOTORE STESSO)` },
  { n: 51, text: `LISTA CONFIGURAZIONE SOFT START` },
  { n: 52, text: `VERIFICA DELLA POMPA PER RIEMPIMENTO DELL'OLIO: TEST DI VERIFICA CON OLIO IDRAULICO PER VERIFICARE IL CORRETTO FUNZIONAMENTO E LA PORTATA` },
  { n: 53, text: `AS BUILT - SCHEMA ELETTRICO` },
  { n: 54, text: `AS BUILT - SOFTWARE` },
  { n: 55, text: `AS BUILT - HMI` },
  { n: 56, text: `LISTA ALLARMI / PRIMO INTERVENTO` },
  { n: 57, text: `DOC. PANNELLO MOTORE TAGLIANDO` },
  { n: 58, text: `TEST PROLUNGATO FUNZIONAMENTO MACCHINA (MIN. 2H). VERIFICARE CHE NON CI SIANO PROBLEMI DI COMUNICAZIONE TRA CENTRALINA MOTORE DIESEL E PANNELLO DI CONTROLLO, PERDITE OLIO ECC…` },
  { n: 59, text: `REGISTRAZIONE TRACE,PRESSIONI,ETC.` },
  { n: 60, text: `VERIFICARE LINGUA LISTA ALLARMI` },
  { n: 61, text: `FINE COLLAUDO IMPOSTARE 100% BAR` },
  { n: 62, text: `ARCHIVIARE PLC` },
  { n: 63, text: `VERIFICA COLLEGAMENTO LAN COMAP` },
];
